// enums.gs — constantes de dominio: roles, estados, categorías, convocatorias.

var ROLES = {
  COORDINADOR: 'COORDINADOR',
  WEBMASTER: 'WEBMASTER',
  SUPERVISOR: 'SUPERVISOR',
  EDITOR: 'EDITOR',
  AUTOR: 'AUTOR',
};

var ROLES_GESTORES = [ROLES.COORDINADOR, ROLES.WEBMASTER, ROLES.SUPERVISOR];
var ROLES_INTERNOS = ROLES_GESTORES.concat([ROLES.EDITOR]);

var ESTADOS = {
  RECIBIDO: 'RECIBIDO',
  PRESELECCIONADO: 'PRESELECCIONADO',
  EN_REVISION: 'EN_REVISIÓN',
  CORRECCIONES_SOLICITADAS: 'CORRECCIONES_SOLICITADAS',
  ESPERANDO_APROBACION: 'ESPERANDO_APROBACIÓN',
  CONSULTA_AUTOR: 'CONSULTA_AUTOR',
  APROBADO: 'APROBADO',
  PUBLICADO: 'PUBLICADO',
  RECHAZADO_POR_AUTOR: 'RECHAZADO_POR_AUTOR',
  DESCARTADO: 'DESCARTADO',
};

var CATEGORIA_DEFAULT = 'Sin clasificar';

var CONVOCATORIAS = {
  GENERAL: 'general',
  DOCENTES: 'docentes',
};
